name: Test application deployment

on:
  workflow_dispatch:

jobs:
  test-app:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List all Azure resources
        run: |
          echo "Listing all resources in the subscription..."
          az resource list \
            --query "[].{Name:name, Type:type, ResourceGroup:resourceGroup, Location:location}" \
            -o table

      - name: List Container App Environments
        run: |
          echo "Listing all Container App Environments in the subscription..."
          az containerapp env list -o table

      - name: Check MySQL status
        run: |
            echo "Checking MySQL status..."         
            az mysql flexible-server show \
              --resource-group orders-rg-app-dev-westus2-01 \
              --name orders-mysqlserver-dev -o table

      - name: Check MySQL databases 
        run: |
          echo "Checking MySQL databases..."
          az mysql flexible-server db list \
            --resource-group orders-rg-app-dev-westus2-01 \
            --server-name orders-mysqlserver-dev \
            -o table

      - name: Get MySQL firewall rules
        run: |
            echo "Getting MySQL firewall rules..."    
            az mysql flexible-server firewall-rule list \
            --resource-group orders-rg-app-dev-westus2-01 \
            --name orders-mysqlserver-dev -o table

      - name: Check Grafana replicas
        run: |
          echo "Checking Grafana replicas and status..."
          az containerapp revision list \
            --name orders-grafana-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query "[].{Revision:name, Active:properties.replicas, Running:properties.runningState, Provisioning:properties.provisioningState, Health:properties.healthState}" \
            -o table


      - name: Get Grafana CA latest logs
        run: |
          echo "Getting Grafana CA latest logs..."
          az containerapp logs show \
            --name orders-grafana-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --tail 200

      - name: Get backend CA environment variables
        run: |
          echo "Getting backend CA environment variables..."
          az containerapp show \
            --name orders-backend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query "properties.template.containers[0].env" \
            -o json

      - name: Get Backend CA latest logs
        run: |
          echo "Getting Backend CA latest logs..."
          az containerapp logs show \
            --name orders-backend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --tail 200            

      - name: Get Prometheus CA latest logs
        run: |
          echo "Getting Prometheus CA latest logs..."
          az containerapp logs show \
            --name orders-prometheus-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --tail 200      

      - name: Set environment variables
        run: |
          echo "FRONTEND_URL=$(az containerapp show \
            --name orders-frontend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query properties.configuration.ingress.fqdn -o tsv)" >> $GITHUB_ENV
          echo "BACKEND_URL=$(az containerapp show \
            --name orders-backend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query properties.configuration.ingress.fqdn -o tsv)" >> $GITHUB_ENV
          echo "PROMETHEUS_URL=$(az containerapp show \
            --name orders-prometheus-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query properties.configuration.ingress.fqdn -o tsv)" >> $GITHUB_ENV          
          echo "GRAFANA_URL=$(az containerapp show \
            --name orders-grafana-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query properties.configuration.ingress.fqdn -o tsv)" >> $GITHUB_ENV

           
      - name: Test Frontend HTTP response
        run: |
          echo "Testing frontend at $FRONTEND_URL ..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$FRONTEND_URL)
          echo "Frontend HTTP status: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Frontend health check failed!"
            exit 1
          fi
          echo "Frontend health check passed."

      - name: Check backend replicas
        run: |
          echo "Checking backend replicas..."
          az containerapp revision list \
            --name orders-backend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query "[].{name:name, active:activeReplicas}" \
            -o table

      - name: Check backend app status
        run: |
          STATUS=$(az containerapp show \
            --name orders-backend-dev-01 \
            --resource-group orders-rg-app-dev-westus2-01 \
            --query "properties.provisioningState" -o tsv)
          echo "Backend provisioning state: $STATUS"
          if [ "$STATUS" != "Succeeded" ]; then
            echo "Backend is not ready!"
            exit 1
          fi

      - name: Test Backend HTTP response
        run: |
          echo "Testing backend at $BACKEND_URL ..."
          
          MAX_RETRIES=10
          SLEEP=5
          
          for i in $(seq 1 $MAX_RETRIES); do
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$BACKEND_URL/actuator/health)
            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "Backend health check passed."
              exit 0
            fi
            echo "Attempt $i/$MAX_RETRIES: Backend not ready yet (status $STATUS_CODE), retrying in $SLEEP sec..."
            sleep $SLEEP
          done

          echo "Backend health check failed after $MAX_RETRIES attempts!"
          exit 1

      - name: Test Prometheus HTTP response
        run: |
          echo "Testing Prometheus at $PROMETHEUS_URL ..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$PROMETHEUS_URL/query)
          echo "Prometheus HTTP status: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Prometheus health check failed!"
            exit 1
          fi
          echo "Prometheus health check passed."            

      - name: Test Grafana HTTP response
        run: |
          echo "Testing Grafana at $GRAFANA_URL ..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$GRAFANA_URL/login)
          echo "Grafana HTTP status: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Grafana health check failed!"
            exit 1
          fi
          echo "Grafana health check passed."              