name: Test MySQL and Grafana Setup

on:
  workflow_dispatch:

jobs:
  test-mysql-grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Check databases created in MySQL
        run: |
          echo "Listing databases in Flexible Server..."
          az mysql flexible-server db list \
            --resource-group orders-rg-app-dev-westus2-01 \
            --server-name orders-mysqlserver-dev \
            -o table

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Test MySQL connection from runner
        run: |
          echo "Testing MySQL connection..."
          mysql -h orders-mysqlserver-dev.mysql.database.azure.com -u grafanaadmin@orders-mysqlserver-dev -p 112
          echo "Testing MySQL connection 2..."
          echo "SELECT NOW();" | mysql \
            -h orders-mysqlserver-dev.mysql.database.azure.com \
            -u grafanaadmin@orders-mysqlserver-dev \
            -p"${{ secrets.MYSQL_PASSWORD }}" \
            -D grafana \
            --ssl-mode=REQUIRED